# Generated by Django 4.1.4 on 2023-10-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeetr', '0006_profile_homepage_link_profile_instgaram_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instgaram_link',
            new_name='instagaram_link',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='prfile_bio',
            new_name='profile_bio',
        ),
    ]
