# Generated by Django 4.1.4 on 2023-10-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeetr', '0007_rename_instgaram_link_profile_instagaram_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='homepage_link',
            new_name='website_link',
        ),
    ]
