# Generated by Django 4.1.4 on 2023-10-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweeetr', '0008_rename_homepage_link_profile_website_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instagaram_link',
            new_name='instagram_link',
        ),
    ]
